version: '3'
services:
  commentators:
    container_name: commentators
    build:
      context: .
    ports:
      - "8888:80"
    volumes:
      - ./src:/app
      - ./contexts:/app/contexts
    command: /start-reload.sh
